
name: Build and release
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event.action == 'published'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      if: github.event.action == 'published'
      run: mvn clean compile install
    - uses: meeDamian/github-release@1.0
      if: github.event.action == 'published'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: target/com.saunderstheaterproperties.utils.jar
        allow_override: true
